#!/bin/bash



# i3 workspaces
# 1nd monitor
# {"1:","2:","3: ","4: ","5: ","6: ","7: ","8:♫ "}
# 2nd monitor
# {"11:","12:","13: ","14: ","15: ","16: ","17: ","18:♫ "}




# # switch to workspace
super + {1-8}
  i3-msg workspace {"1:","2:","3: ","4: ","5: ","6: ","7: ","8:♫ "}

# move focused container to workspace
super + shift + {1-8}
  i3-msg move container to workspace {"1:","2:","3: ","4: ","5: ","6: ","7: ","8:♫ "}

# # switch to workspace monitor 2
super + ctrl + {1-8}
  i3-msg workspace number {"11:","12:","13: ","14: ","15: ","16: ","17: ","18:♫ "}

# move focused container to workspace monitor 2
super + ctrl +shift + {1-8}
  i3-msg move container to workspace {"11:","12:","13: ","14: ","15: ","16: ","17: ","18:♫ "}


# Lock screen
super + 9 
  exec blurlock


# workspace back and forth (with/without active container)
super +b 
  i3-msg workspace back_and_forth
super + shift +b 
  i3-msg move container to workspace back_and_forth; \
  i3-msg workspace back_and_forth

# split orientation
super +h 
  i3-msg split h;exec notify-send 'tile horizontally'
super +v 
  i3-msg split v;exec notify-send 'tile vertically'
super +q 
  i3-msg split toggle

# toggle fullscreen mode for the focused container
super +f 
  i3-msg fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
super +s 
  i3-msg layout stacking
super +w 
  i3-msg layout tabbed
super +e 
  i3-msg layout toggle split

# toggle tiling / floating
super + shift +space 
  i3-msg floating toggle

# change focus between tiling / floating windows
super +space 
  i3-msg focus mode_toggle

# toggle sticky
super + shift +s 
  i3-msg sticky toggle

# focus the parent container
super +a 
  i3-msg focus parent

# move the currently focused window to the scratchpad
super + shift +minus 
  i3-msg move scratchpad

# Show the next scratchpad window or hide the focused scratchpad window.
# If there are multiple scratchpad windows, this command cycles through them.
super +minus 
  i3-msg scratchpad show

#navigate workspaces next / previous
super + ctrl + Right 
  i3-msg workspace next
super + ctrl + Left 
  i3-msg workspace prev







# hide/unhide i3status bar
super+m 
  i3-msg bar mode toggle




# ------------------------ #

# change borders
super + u
  i3-msg  border none
super + y
  i3-msg  border pixel 1
super + n
  i3-msg  border normal


# start a terminal
super + Return 
  exec kitty

# kill focused window
super + shift + q
  i3-msg  kill

# start program launcher
#super +d exec dmenu_recency
super + d 
  exec ~/.config/rofi/rofi-launcher.sh
# launch categorized menu
super + z 
  exec morc_menu

# ------------------------ #






# change keyboard layout 
Shift_L + alt
  exec ~/.config/i3/scripts/keyboard_layout_switch.sh

# change wallpaper
#Super_L + shift_L + i
#  feh --bg-max --randomize ./Pictures/wallpapers/dota2/

# open configs (nvim-by-fzf)
super + alt + c
	exec kitty nvim-by-fzf





# reload the configuration file
super + shift + c
  i3-msg  reload

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
super + shift + r
  i3-msg  restart


super + ctrl + m 
  exec kitty -e 'alsamixer'








# ----------- #
# Start Applications
super + ctrl+b 
  exec kitty -e 'bmenu'

super + F1 
  exec code
super + F2 
  exec brave
#pcmanfm
super + F3 
  exec thunar 
# super + F3 exec ranger

super + shift+F3 
  exec pcmanfm_pkexec

#idk wtf is mocp
#super + F5 
#  exec kitty -e 'mocp'

# picom
super + t 
  pkill picom; \
  notify-send 'Picom Killed. use Mod+Ctrl+t to start again'
super + ctrl+t 
  picom -b; \
  notify-send 'Picom Started. use Mod+t to stop again'
  
super + shift+d
  killall dunst; \
  notify-send 'Restart Dunst'


# screenshots
Print 
  i3-msg exec i3-scrot
super + Print
  exec i3-scrot -w
super + shift+Print
  exec i3-scrot -s

# open help
super + shift + h
  exec xdg-open /usr/share/doc/manjaro/i3_help.pdf
super + ctrl + x
  exec xkill

# find window name
super + ctrl + z
  exec "xprop > ~/Desktop/xprop.txt; kitty nvim ~/Desktop/xprop.txt"

# color picker, saves colorHex in clipboard
super + ctrl + c
  exec xcolor -s clipboard

# ----------- #
