#!/bin/sh

intern="eDP-1"
extern="HDMI-1"

case "$1" in
  "disconnect") xrandr --output "$extern" --off --output "$intern" --auto ;;
  "extra") xrandr --output "$extern" --set audio force-dvi --mode 1920x1080 && xrandr --output "$intern" --auto --output "$extern" --right-of "$intern" ;;
  "duplicate") xrandr --output "$extern" --set audio force-dvi --mode 1920x1080 && xrandr --output "$intern" --auto --output "$extern" --right-of "$intern" ;;
  *) echo "Mutli Monitor: Unknow Operation..."
esac


